### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by erolrecep** [bulutyazilim/awesome-datascience#84]
I can not push to repo. It says permission denied.
<img width="708" alt="screen shot 2016-11-09 at 11 32 42 am" src="https://cloud.githubusercontent.com/assets/4239092/20148052/6be9abe6-a670-11e6-83be-6eb34b169cec.png">

**Comment by hmert** [comment]
I re-invite you as main collaborator. It may occurs because of public key changes of the repo.
